const GOALS = {
  quick_lunch: {
    label: 'Quick lunch',
    description: 'A fast, practical combo with fewer items and sensible price.',
  },
  high_protein: {
    label: 'High protein',
    description: 'A protein-focused combo using menu items rich in protein.',
  },
  under_200: {
    label: 'Under ₹200',
    description: 'A satisfying combo that stays within ₹200 total.',
  },
};

const PROTEIN_KEYWORDS = [
  'protein',
  'paneer',
  'chicken',
  'egg',
  'soy',
  'dal',
  'lentil',
  'tofu',
  'chickpea',
  'rajma',
  'fish',
  'grilled',
];

const QUICK_KEYWORDS = [
  'wrap',
  'roll',
  'sandwich',
  'burger',
  'bowl',
  'combo',
  'meal',
  'fries',
  'snack',
];

const normalizeGoal = (goal = '') => {
  // Normalize common user text to one internal key so rest of logic stays simple.
  const value = String(goal).trim().toLowerCase();
  if (value === 'quick lunch' || value === 'quick_lunch') return 'quick_lunch';
  if (value === 'high protein' || value === 'high_protein') return 'high_protein';
  if (value === 'under 200' || value === 'under_200' || value === 'under ₹200' || value === 'under rs 200') {
    return 'under_200';
  }
  return value;
};

const tokenize = (item) => {
  const text = `${item.name || ''} ${item.description || ''} ${item.category || ''}`.toLowerCase();
  return text;
};

const scoreItem = (item, goal) => {
  const text = tokenize(item);
  const price = Number(item.price || 0);

  let score = 0;
  if (goal === 'high_protein') {
    if (PROTEIN_KEYWORDS.some((keyword) => text.includes(keyword))) score += 10;
    if (price >= 90 && price <= 260) score += 2;
    if (item.is_veg) score += 1;
  }

  if (goal === 'quick_lunch') {
    if (QUICK_KEYWORDS.some((keyword) => text.includes(keyword))) score += 8;
    if (price <= 220) score += 2;
  }

  if (goal === 'under_200') {
    if (price <= 120) score += 5;
    if (price <= 200) score += 3;
    if (PROTEIN_KEYWORDS.some((keyword) => text.includes(keyword))) score += 1;
  }

  // Small tie-breakers for more stable results.
  if (item.is_available === false) score -= 100;
  if (!item.name) score -= 5;

  return score;
};

const chooseFallbackCombo = ({ menuItems, goal }) => {
  // Step 1: score and sort all menu items.
  const sorted = [...menuItems]
    .map((item) => ({ ...item, __score: scoreItem(item, goal) }))
    .sort((a, b) => b.__score - a.__score || Number(a.price) - Number(b.price));

  // Step 2: simple budget and max-items rules per goal.
  const budget = goal === 'under_200' ? 200 : goal === 'quick_lunch' ? 350 : 500;
  const maxItems = goal === 'quick_lunch' ? 2 : 3;

  // Step 3: pick items in order while respecting goal constraints.
  const picked = [];
  let total = 0;

  for (const item of sorted) {
    if (picked.length >= maxItems) break;
    const nextTotal = total + Number(item.price || 0);
    if (nextTotal > budget) continue;
    picked.push(item);
    total = nextTotal;
  }

  // Ensure at least one item so the user always gets a response.
  if (picked.length === 0 && sorted.length > 0) {
    picked.push(sorted[0]);
    total = Number(sorted[0].price || 0);
  }

  return {
    combo_name: `${GOALS[goal]?.label || 'Smart'} Combo`,
    items: picked.map((item) => ({
      id: item.id,
      name: item.name,
      price: Number(item.price || 0),
      category: item.category || null,
      is_veg: Boolean(item.is_veg),
      reason: goal === 'high_protein'
        ? 'Selected for better protein-to-price balance.'
        : goal === 'under_200'
          ? 'Selected to keep total cost within budget.'
          : 'Selected for quick and practical lunch value.',
    })),
    total_price: total,
    used_ai: false,
    explanation: 'Generated by deterministic fallback scoring using goal constraints.',
  };
};

const parseGeminiJson = (text) => {
  if (!text || typeof text !== 'string') return null;
  const trimmed = text.trim();

  try {
    return JSON.parse(trimmed);
  } catch {
    // Sometimes models wrap JSON in markdown, so we safely parse that too.
    const match = trimmed.match(/```json\s*([\s\S]*?)```/i) || trimmed.match(/```([\s\S]*?)```/i);
    if (!match) return null;
    try {
      return JSON.parse(match[1].trim());
    } catch {
      return null;
    }
  }
};

const buildGeminiPrompt = ({ goal, restaurantName, menuItems }) => {
  const constraint =
    goal === 'under_200'
      ? 'Must keep total combo price <= 200 INR.'
      : goal === 'high_protein'
        ? 'Prioritize higher-protein items and good value.'
        : 'Prioritize quick lunch practicality with up to 2 items.';

  return [
    'You are a food recommendation assistant for a food delivery app.',
    `Goal: ${goal}`,
    `Restaurant: ${restaurantName || 'Unknown restaurant'}`,
    `Constraint: ${constraint}`,
    'Pick a realistic combo from menu items only.',
    'Return strictly valid JSON with this shape:',
    '{',
    '  "combo_name": "string",',
    '  "item_ids": ["id1", "id2"],',
    '  "reasons": ["short reason per item"],',
    '  "overall_explanation": "short explanation"',
    '}',
    'Rules:',
    '- Pick 1 to 3 items max.',
    '- Never use items outside provided menu.',
    '- Keep reasons practical and constraint-based.',
    '- No markdown, no extra text.',
    '',
    `Menu JSON: ${JSON.stringify(menuItems)}`,
  ].join('\n');
};

const callGemini = async ({ apiKey, goal, restaurantName, menuItems }) => {
  // If key is missing, caller will naturally fall back to local rule-based logic.
  if (!apiKey) return null;

  const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [{ parts: [{ text: buildGeminiPrompt({ goal, restaurantName, menuItems }) }] }],
      generationConfig: {
        temperature: 0.3,
        topP: 0.9,
        maxOutputTokens: 700,
      },
    }),
  });

  if (!response.ok) {
    const body = await response.text();
    throw new Error(`Gemini API failed (${response.status}): ${body.slice(0, 180)}`);
  }

  const data = await response.json();
  const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
  return parseGeminiJson(text);
};

const buildComboFromAiResult = ({ aiResult, menuItems, goal }) => {
  if (!aiResult || !Array.isArray(aiResult.item_ids)) return null;

  const reasons = Array.isArray(aiResult.reasons) ? aiResult.reasons : [];
  const menuMap = new Map(menuItems.map((item) => [item.id, item]));

  const picked = aiResult.item_ids
    .slice(0, 3)
    .map((id, index) => {
      const item = menuMap.get(id);
      if (!item) return null;
      return {
        id: item.id,
        name: item.name,
        price: Number(item.price || 0),
        category: item.category || null,
        is_veg: Boolean(item.is_veg),
        reason: reasons[index] || 'Chosen based on your selected goal and item constraints.',
      };
    })
    .filter(Boolean);

  if (picked.length === 0) return null;

  const total = picked.reduce((sum, item) => sum + Number(item.price || 0), 0);

  // Hard safety check for under_200 goal.
  if (goal === 'under_200' && total > 200) {
    return null;
  }

  return {
    combo_name: aiResult.combo_name || `${GOALS[goal]?.label || 'Smart'} Combo`,
    items: picked,
    total_price: total,
    used_ai: true,
    explanation: aiResult.overall_explanation || 'Generated using Gemini based on menu constraints.',
  };
};

const suggestSmartCombo = async ({ restaurantName, menuItems, goal }) => {
  const normalizedGoal = normalizeGoal(goal);
  if (!GOALS[normalizedGoal]) {
    throw new Error('Unsupported goal. Use quick_lunch, high_protein, or under_200.');
  }

  if (!Array.isArray(menuItems) || menuItems.length === 0) {
    return {
      goal: normalizedGoal,
      combo_name: `${GOALS[normalizedGoal].label} Combo`,
      items: [],
      total_price: 0,
      explanation: 'No available menu items found for this restaurant.',
      used_ai: false,
    };
  }

  // Keep payload short and predictable for stable AI responses.
  const compactMenu = menuItems.slice(0, 60).map((item) => ({
    id: item.id,
    name: item.name,
    description: item.description || '',
    price: Number(item.price || 0),
    category: item.category || '',
    is_veg: Boolean(item.is_veg),
    is_available: item.is_available !== false,
  }));

  const apiKey = process.env.GEMINI_API_KEY;

  try {
    const aiResult = await callGemini({
      apiKey,
      goal: normalizedGoal,
      restaurantName,
      menuItems: compactMenu,
    });

    const builtFromAi = buildComboFromAiResult({
      aiResult,
      menuItems: compactMenu,
      goal: normalizedGoal,
    });

    if (builtFromAi) {
      return {
        goal: normalizedGoal,
        ...builtFromAi,
      };
    }
  } catch (error) {
    // AI failures should not break user experience, so we use fallback combo.
    console.warn('Gemini combo suggestion failed, using fallback:', error.message);
  }

  return {
    goal: normalizedGoal,
    ...chooseFallbackCombo({ menuItems: compactMenu, goal: normalizedGoal }),
  };
};

module.exports = {
  GOALS,
  normalizeGoal,
  suggestSmartCombo,
};
